name: ghs

on:
    push:
        paths: 
            - ".github/workflows/ghs.yml"
    workflow_dispatch: # manual
    

jobs:
    cli:
        runs-on: ubuntu-latest
        env:
            gh_token: ${{ secrets.GITHUB_TOKEN}}
        steps:
            - uses: actions/checkout@v4
            - run: env
            - run: gh --version
            - run: gh auth status
            - run: gh repo list
            - run: gh workflow list 
            - run: api /repos/:owner/:repo/actions/workflow

    